apiVersion: v1
kind: Service
metadata:
  name: redis-nodeport
  namespace: redis
  labels:
    app: redis
spec:
  ports:
    - name: redis
      port: 6379
      protocol: TCP
      targetPort: 6379
      nodePort: 31003
  type: NodePort
  selector:
    app: redis
