apiVersion: apps/v1
kind: Deployment
metadata:
  name: camus
spec:
  selector:
    matchLabels:
      app: camus
  replicas: 1
  template:
    metadata:
      labels:
        app: camus
    spec:
      containers:
        - name: camus
          image: camuschat/camus:latest
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
      restartPolicy: Always
