apiVersion: v1
kind: Pod
metadata:
  name: zdir
spec:
  containers:
    - name: zdir
      image: helloz/zdir:latest
      ports:
        - containerPort: 6080
      volumeMounts:
        - name: zdir-data
          mountPath: /data/apps/zdir/data
        - name: zdir-public
          mountPath: /data/apps/zdir/data/public
      restartPolicy: Always
  volumes:
    - name: zdir-data
      hostPath:
        path: /volume1/docker/zdir
    - name: zdir-public
      hostPath:
        path: /volume1/docker/zdir