apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # creationTimestamp: null
  name: aria2-claim0
  namespace: aria2
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
status: {}
