apiVersion: v1
kind: Service
metadata:
  name: heimdall-service
  namespace: heimdall
  labels:
    app: heimdall
spec:
  ports:
  - name: http
    targetPort: 80 # pod中的
    port: 80 # service的
    nodePort: 41016
  - name: https
    targetPort: 443 # pod中的
    port: 443 # service的
    nodePort: 44016
  type: NodePort
  selector:
     app: heimdall