apiVersion: v1
kind: Service
metadata:
  name: redis-single
  namespace: redis-single
  labels:
    app: redis-single
spec:
  type: NodePort
  ports:
    - name: tcp
      port: 6379
      nodePort: 31004
  selector:
    app: redis-single
