apiVersion: v1
kind: Service
metadata:
  name: statping-service
  namespace: statping
  labels:
    app: statping
spec:
  ports:
  - targetPort: 8080  # pod中的
    port: 8080  # service的
    nodePort: 41020
  type: NodePort
  selector:
     app: statping