apiVersion: v1
kind: Service
metadata:
  name: vw-service
  namespace: vw
  labels:
    app: vw
spec:
  ports:
  - targetPort: 80
    port: 5280
    nodePort: 41004
  type: NodePort
  selector:
     app: vw