apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # creationTimestamp: null
  name: onenav-claim0
  namespace: onenav
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Mi
status: {}
