apiVersion: v1
kind: Service
metadata:
  name: pdftoolbox-service
  namespace: pdftoolbox
  labels:
    app: pdftoolbox
spec:
  ports:
  - targetPort: 8082 # pod中的
    port: 8082 # service的
    nodePort: 41010
  type: NodePort
  selector:
     app: pdftoolbox