kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-claim
spec:
  # storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
    # - ReadWriteMany
    # - ReadWriteMany
    # ReadWriteOnce -- 该volume只能被单个节点以读写的方式映射
    # ReadOnlyMany -- 该volume可以被多个节点以只读方式映射
    # ReadWriteMany -- 该volume可以被多个节点以读写的方式映射
  resources:
    requests:
      storage: 1Mi
