apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # creationTimestamp: null
  name: homer-claim0
  namespace: homer
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
status: {}
