apiVersion: v1
kind: Service
metadata:
  name: homer-service
  namespace: homer
  labels:
    app: homer
spec:
  ports:
  - targetPort: 8080 # pod中的
    port: 8080 # service的
    nodePort: 41007
  type: NodePort
  selector:
     app: homer