apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # creationTimestamp: null
  name: gopeed-claim0
  namespace: gopeed
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Mi
status: {}
