apiVersion: v1
kind: Service
metadata:
  name: gopeed-service
  namespace: gopeed
  labels:
    app: gopeed
spec:
  ports:
  - targetPort: 9999 # pod中的
    port: 9999 # service的
    nodePort: 41015
  type: NodePort
  selector:
     app: gopeed