apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: mysql
  labels:
    app: mysql
spec:
  ports:
  - targetPort: 3306 # pod中的
    port: 3306 # service的
    nodePort: 31005
  type: NodePort
  selector:
     app: mysql