apiVersion: v1
kind: Service
metadata:
  name: vocechat-service
  namespace: vocechat
  labels:
    app: vocechat
spec:
  ports:
  - targetPort: 3000
    port: 3000
    nodePort: 41005
  type: NodePort
  selector:
     app: vocechat