apiVersion: v1
kind: Service
metadata:
  name: memos-service
  namespace: memos
  labels:
    app: memos
spec:
  ports:
  - targetPort: 5230
    port: 5230
    nodePort: 41003
  type: NodePort
  selector:
     app: memos