apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o ./k8syaml/
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: memos
  name: memos
spec:
  replicas: 4
  selector:
    matchLabels:
      io.kompose.service: memos
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o ./k8syaml/
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/memos-default: "true"
        io.kompose.service: memos
    spec:
      containers:
        - image: neosmemo/memos:latest
          name: memos
          ports:
            - containerPort: 5230
              hostIP: 127.0.0.1
          resources: {}
          volumeMounts:
            - mountPath: /var/opt/memos
              name: memos-claim0
      restartPolicy: Always
      volumes:
        - name: memos-claim0
          persistentVolumeClaim:
            claimName: memos-claim0
status: {}
