apiVersion: v1
kind: Service
metadata:
  name: excalidraw-service
  namespace: excalidraw
  labels:
    app: excalidraw
spec:
  ports:
  - targetPort: 80 # pod中的
    port: 80 # service的
    nodePort: 41014
  type: NodePort
  selector:
     app: excalidraw