apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # creationTimestamp: null
  name: searxng-claim0
  namespace: searxng
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
status: {}
