apiVersion: apps/v1
kind: Deployment
metadata:
  name: searxng
  namespace: searxng
  labels:
    app: searxng
spec:
  selector:
    matchLabels:
      app: searxng
  replicas: 1
  template:
    metadata:
      labels:
        app: searxng
    spec:
      containers:
        - image: searxng/searxng
          imagePullPolicy: IfNotPresent
          name: searxng
          resources: 
            requests:
              memory: "1024Mi"
              cpu: "512m"
            limits:
              memory: "2048Mi"
              cpu: "2048m"          
          ports:
            - containerPort: 8080
              name: searxng-listin             
          volumeMounts:
            - mountPath: /etc/searxng
              name: searxng-claim0
      volumes:
        - name: searxng-claim0
          persistentVolumeClaim:
            claimName: searxng-claim0
