apiVersion: v1
kind: Service
metadata:
  name: trwebocr-service
  namespace: trwebocr
  labels:
    app: trwebocr
spec:
  ports:
  - targetPort: 8089 # pod中的
    port: 8089 # service的
    nodePort: 41008
  type: NodePort
  selector:
     app: trwebocr