apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # creationTimestamp: null
  name: tachidesk-claim0
  namespace: tachidesk
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Mi
status: {}
